apiVersion: v2
name: wildwest-controller
description: Wild West Controller for KCP
type: application
version: 0.0.0
appVersion: "0.0.0-dev"
sources:
  - https://github.com/platform-mesh/provider-quickstart
dependencies:
  - name: common
    version: 0.13.0
    repository: oci://ghcr.io/platform-mesh/helm-charts
