replicaCount: 1

image:
  repository: ghcr.io/platform-mesh/provider-quickstart
  pullPolicy: IfNotPresent
  tag: "@sha256:3bda1260ec35fa6be20e264ff0bb7e52576a36e3eb97840e1d579325879b2383"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 65532

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

# Controller configuration
controller:
  endpointSlice: "wildwest.platform-mesh.io"

# kcp kubeconfig secret
kubeconfig:
  secretName: "wildwest-controller-kubeconfig"
  secretKey: "kubeconfig"
