{{- if .Values.httpRoute.enabled -}}
{{- if .Values.httpRoute.referenceGrant.enabled -}}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: {{ include "wildwest-portal.fullname" . }}
  labels:
    {{- include "wildwest-portal.labels" . | nindent 4 }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: {{ .Values.httpRoute.referenceGrant.fromNamespace | default .Values.httpRoute.namespace | default "platform-mesh-system" }}
  to:
    - group: ""
      kind: Service
{{- end }}
{{- end }}
