apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  labels:
    ui.platform-mesh.io/content-for: wildwest.platform-mesh.io
  name: wildwest.platform-mesh.io
spec:
  permissionClaims:
  - resource: events
    verbs:
    - '*'
  resources:
  - group: wildwest.platform-mesh.io
    name: armaments
    schema: v260512-977c1bd.armaments.wildwest.platform-mesh.io
    storage:
      virtual:
        identityHash: 2aa635c811395932a55e595f5b1ce91fc25734b0f090ffb81d91e6f73ffbc10b
        reference:
          apiGroup: cache.kcp.io
          kind: CachedResourceEndpointSlice
          name: armaments
  - group: wildwest.platform-mesh.io
    name: cowboys
    schema: v260518-8e27e65.cowboys.wildwest.platform-mesh.io
    storage:
      crd: {}
status: {}
