replicaCount: 1

image:
  repository: ghcr.io/platform-mesh/provider-quickstart-portal
  pullPolicy: IfNotPresent
  tag: "@sha256:2fd3d14130b446acee3ac1d9fef7c1f5f60cb2ceab29d18f04539a2b780abb9a"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  readOnlyRootFilesystem: false
  runAsNonRoot: true
  runAsUser: 101

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: portal.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

httpRoute:
  enabled: false
  hostnames:
    - portal.localhost
    - "*.portal.localhost"
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: k8sapi-gateway
      namespace: platform-mesh-system
  pathPrefix: /cowboys
  filters:
    - extensionRef:
        group: traefik.io
        kind: Middleware
        name: wildwest-portal-cors
      type: ExtensionRef
  referenceGrant:
    enabled: true
    fromNamespace: platform-mesh-system

middleware:
  enabled: false
  corsOrigins:
    - http://localhost:4200
    - http://*.localhost:4200
    - https://portal.localhost:8443
    - https://*.portal.localhost:8443

resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}
